In [21]:
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
csv = pd.read_csv('../../data/basketball-reference/players(25-26)/regular-season/shooting.csv', header=1)
df = pd.DataFrame(csv)
df

,Rk,Player,Age,Team,Pos,G,GS,MP,FG%,Dist.,...,2P.2,3P.2,%FGA,#,%3PA,3P%,Att.,Md.,Awards,-9999
0,1.0,Amen Thompson,23.0,HOU,PG,79.0,79.0,2953.0,0.534,7.8,...,0.530,0.960,0.209,201.0,0.586,0.235,1.0,0.0,DPOY-8,thompam01
1,2.0,Kevin Durant,37.0,HOU,SF,78.0,78.0,2840.0,0.520,16.4,...,0.472,0.731,0.042,54.0,0.102,0.500,0.0,0.0,CPOY-9ASNBA2,duranke01
2,3.0,Desmond Bane,27.0,ORL,SG,82.0,82.0,2756.0,0.484,13.5,...,0.526,0.796,0.002,2.0,0.197,0.440,0.0,0.0,NaN,banede01
3,4.0,Toumani Camara,25.0,POR,PF,82.0,82.0,2731.0,0.440,18.1,...,0.659,0.886,0.051,39.0,0.296,0.331,0.0,0.0,NaN,camarto01
4,5.0,Jabari Smith Jr.,22.0,HOU,PF,77.0,77.0,2705.0,0.450,16.8,...,0.670,0.966,0.069,65.0,0.357,0.374,0.0,0.0,NaN,smithja05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,579.0,Colby Jones,23.0,DET,SG,1.0,0.0,7.0,0.333,16.9,...,0.000,NaN,0.000,0.0,1.000,0.000,0.0,0.0,NaN,jonesco02
730,580.0,Noa Essengue,19.0,CHI,PF,2.0,0.0,6.0,0.000,16.9,...,NaN,NaN,0.000,0.0,0.500,0.000,0.0,0.0,NaN,essenno01
731,581.0,Trentyn Flowers,20.0,CHI,SF,2.0,0.0,6.0,0.667,8.3,...,0.500,NaN,0.333,1.0,1.000,0.000,0.0,0.0,NaN,flowetr01
732,582.0,Darius Brown II,26.0,CLE,SG,1.0,0.0,3.0,0.000,17.5,...,NaN,NaN,0.000,0.0,NaN,NaN,0.0,0.0,NaN,brownda04
733,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,0.471,13.9,...,0.537,0.854,0.061,NaN,0.246,0.387,NaN,NaN,NaN,-9999

I'm not sure I like that the league average has NaN for most of its columns, so I think that deleting and using the .mean() function is just a better choice.

In [23]:
df = df.iloc[:-1]
df

,Rk,Player,Age,Team,Pos,G,GS,MP,FG%,Dist.,...,2P.2,3P.2,%FGA,#,%3PA,3P%,Att.,Md.,Awards,-9999
0,1.0,Amen Thompson,23.0,HOU,PG,79.0,79.0,2953.0,0.534,7.8,...,0.530,0.960,0.209,201.0,0.586,0.235,1.0,0.0,DPOY-8,thompam01
1,2.0,Kevin Durant,37.0,HOU,SF,78.0,78.0,2840.0,0.520,16.4,...,0.472,0.731,0.042,54.0,0.102,0.500,0.0,0.0,CPOY-9ASNBA2,duranke01
2,3.0,Desmond Bane,27.0,ORL,SG,82.0,82.0,2756.0,0.484,13.5,...,0.526,0.796,0.002,2.0,0.197,0.440,0.0,0.0,NaN,banede01
3,4.0,Toumani Camara,25.0,POR,PF,82.0,82.0,2731.0,0.440,18.1,...,0.659,0.886,0.051,39.0,0.296,0.331,0.0,0.0,NaN,camarto01
4,5.0,Jabari Smith Jr.,22.0,HOU,PF,77.0,77.0,2705.0,0.450,16.8,...,0.670,0.966,0.069,65.0,0.357,0.374,0.0,0.0,NaN,smithja05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,578.0,Stanley Umude,26.0,SAS,SG,2.0,0.0,7.0,0.500,16.4,...,1.000,NaN,0.000,0.0,1.000,0.000,0.0,0.0,NaN,umudest01
729,579.0,Colby Jones,23.0,DET,SG,1.0,0.0,7.0,0.333,16.9,...,0.000,NaN,0.000,0.0,1.000,0.000,0.0,0.0,NaN,jonesco02
730,580.0,Noa Essengue,19.0,CHI,PF,2.0,0.0,6.0,0.000,16.9,...,NaN,NaN,0.000,0.0,0.500,0.000,0.0,0.0,NaN,essenno01
731,581.0,Trentyn Flowers,20.0,CHI,SF,2.0,0.0,6.0,0.667,8.3,...,0.500,NaN,0.333,1.0,1.000,0.000,0.0,0.0,NaN,flowetr01
732,582.0,Darius Brown II,26.0,CLE,SG,1.0,0.0,3.0,0.000,17.5,...,NaN,NaN,0.000,0.0,NaN,NaN,0.0,0.0,NaN,brownda04

In [25]:
print(df.columns) # Hate these dataframe column names
df = df.rename(columns={
    '2P': 'fga%_2P', '0-3': 'fga%_0-3', '3-10': 'fga%_3-10', '10-16': 'fga%_10-16', '16-3P': 'fga%_16-3P', '3P': 'fga%_3P',
    '2P.1': 'fg%_2P', '0-3.1': 'fg%_0-3', '3-10.1': 'fg%_3-10', '10-16.1': 'fg%_10-16', '16-3P.1': 'fg%_16-3P', '3P.1': 'fg%_3P',
    '2P.2': 'ast%_2P', '3P.2': 'ast%_3P',
    '%FGA': 'dunk_fga%', '#': 'dunks_made',
    '%3PA': 'corner_3pa%', '3P%': 'corner_3p%',
    'Att.': 'heave_att', 'Md.': 'heave_made',
    '-9999': 'player_id',
})
print(df.columns)
df

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG%', 'Dist.',
       'fga%_2P', 'fga%_0-3', 'fga%_3-10', 'fga%_10-16', 'fga%_16-3P',
       'fga%_3P', 'fg%_2P', 'fg%_0-3', 'fg%_3-10', 'fg%_10-16', 'fg%_16-3P',
       'fg%_3P', 'ast%_2P', 'ast%_3P', 'dunk_fga%', 'dunks_made',
       'corner_3pa%', 'corner_3p%', 'heave_att', 'heave_made', 'Awards',
       'player_id'],
      dtype='str')
Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG%', 'Dist.',
       'fga%_2P', 'fga%_0-3', 'fga%_3-10', 'fga%_10-16', 'fga%_16-3P',
       'fga%_3P', 'fg%_2P', 'fg%_0-3', 'fg%_3-10', 'fg%_10-16', 'fg%_16-3P',
       'fg%_3P', 'ast%_2P', 'ast%_3P', 'dunk_fga%', 'dunks_made',
       'corner_3pa%', 'corner_3p%', 'heave_att', 'heave_made', 'Awards',
       'player_id'],
      dtype='str')

,Rk,Player,Age,Team,Pos,G,GS,MP,FG%,Dist.,...,ast%_2P,ast%_3P,dunk_fga%,dunks_made,corner_3pa%,corner_3p%,heave_att,heave_made,Awards,player_id
0,1.0,Amen Thompson,23.0,HOU,PG,79.0,79.0,2953.0,0.534,7.8,...,0.530,0.960,0.209,201.0,0.586,0.235,1.0,0.0,DPOY-8,thompam01
1,2.0,Kevin Durant,37.0,HOU,SF,78.0,78.0,2840.0,0.520,16.4,...,0.472,0.731,0.042,54.0,0.102,0.500,0.0,0.0,CPOY-9ASNBA2,duranke01
2,3.0,Desmond Bane,27.0,ORL,SG,82.0,82.0,2756.0,0.484,13.5,...,0.526,0.796,0.002,2.0,0.197,0.440,0.0,0.0,NaN,banede01
3,4.0,Toumani Camara,25.0,POR,PF,82.0,82.0,2731.0,0.440,18.1,...,0.659,0.886,0.051,39.0,0.296,0.331,0.0,0.0,NaN,camarto01
4,5.0,Jabari Smith Jr.,22.0,HOU,PF,77.0,77.0,2705.0,0.450,16.8,...,0.670,0.966,0.069,65.0,0.357,0.374,0.0,0.0,NaN,smithja05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,578.0,Stanley Umude,26.0,SAS,SG,2.0,0.0,7.0,0.500,16.4,...,1.000,NaN,0.000,0.0,1.000,0.000,0.0,0.0,NaN,umudest01
729,579.0,Colby Jones,23.0,DET,SG,1.0,0.0,7.0,0.333,16.9,...,0.000,NaN,0.000,0.0,1.000,0.000,0.0,0.0,NaN,jonesco02
730,580.0,Noa Essengue,19.0,CHI,PF,2.0,0.0,6.0,0.000,16.9,...,NaN,NaN,0.000,0.0,0.500,0.000,0.0,0.0,NaN,essenno01
731,581.0,Trentyn Flowers,20.0,CHI,SF,2.0,0.0,6.0,0.667,8.3,...,0.500,NaN,0.333,1.0,1.000,0.000,0.0,0.0,NaN,flowetr01
732,582.0,Darius Brown II,26.0,CLE,SG,1.0,0.0,3.0,0.000,17.5,...,NaN,NaN,0.000,0.0,NaN,NaN,0.0,0.0,NaN,brownda04

df